<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>drv</string>
	</array>
	<key>name</key>
	<string>Oracle adpatch Driver</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant-numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant-language</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#delimiter</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifier</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#text</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*+(#).*$</string>
					<key>name</key>
					<string>comment.line</string>
				</dict>
			</array>
		</dict>
		<key>constant-language</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)(\s|(?&lt;==))(ap|fnd|en|generic|none|odf|p(ackage|df)|s(equences|oftware|qlap)|t(ables|emplate)|u(pload|s(7ascii)?)|views|yes)\b</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</array>
		</dict>
		<key>constant-numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;!/)\b(\d++)\b</string>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</array>
		</dict>
		<key>delimiter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(/|\.|&amp;|=|:|@|-)</string>
					<key>name</key>
					<string>keyword.other.delimiter</string>
				</dict>
			</array>
		</dict>
		<key>identifier</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(bug_\d++)\b</string>
					<key>name</key>
					<string>variable.other</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(\w++)(?==)</string>
					<key>name</key>
					<string>variable.other</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(?&lt;=@|&amp;|-)(\w++)</string>
					<key>name</key>
					<string>variable.other</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)(^|\s)(a(ctions|ru)|b(ase(d)?|egin|ug)|c(h(aracterset|eckfile)|o(mpatible|py))|e(nd|x(ec|tension))|f(eature|ixes|ndload)|genrep|includes|java|on|p(atch_type|latform|roduct)|re(cordpatch|lease|quires_translation)|sql(plus)?|trackable_entity|y)\b</string>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</array>
		</dict>
		<key>text</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\S</string>
					<key>name</key>
					<string>string.quoted.single</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.oracle.driver</string>
	<key>uuid</key>
	<string>8a0e417e-97a9-4442-9c87-3575a06538b6</string>
</dict>
</plist>
