<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ctl</string>
	</array>
	<key>name</key>
	<string>Oracle SQL*Loader</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#options</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#load</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#infile</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#concatenate</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#into</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#condition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#delim</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#termination</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enclosure</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#oid</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sid</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#col</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#parens</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant-numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#delimiter</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifier</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bfile</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(bfile)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>col</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(as|column|object|treat)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>collection</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(boundfiller)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nested</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#varray</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sdf</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#count</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*+(--).*$</string>
					<key>name</key>
					<string>comment.line</string>
				</dict>
			</array>
		</dict>
		<key>concatenate</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(con(catenate|tinueif)|last|next|preserve|this)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>condition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(and)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(blanks)\b</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(!|=|&lt;|&gt;)</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</array>
		</dict>
		<key>constant-numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;!/)\b(\d++)\b</string>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</array>
		</dict>
		<key>count</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(count)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>datatype</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(byteint|char|d(a(te|y)|ecimal|ouble)|external|float|graphic|inte(ger|rval)|lo(cal|ng)|month|number|raw|s(econd|igned|mallint)|t(ime(stamp)?|o)|unsigned|var(char(c)?|graphic|raw(c)?)|with|year|zone(d)?)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delim</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#termination</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#condition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#filler</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enclosure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#init</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scalar</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nested</string>
				</dict>
			</array>
		</dict>
		<key>delim</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(optionally)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>delimiter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\.|\*)</string>
					<key>name</key>
					<string>keyword.other.delimiter</string>
				</dict>
			</array>
		</dict>
		<key>dgen</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(constant|expression|recnum|s(equence|ysdate))\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>enclosure</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(and|by|enclosed)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>filler</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(boundfiller|filler|pieced)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>identifier</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(")(?=([^"]){0,30}")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.delimiter</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(")</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variable-other-substitution-oracle-sqlplus</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>variable.other</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(")(?=([^"]){31,}")</string>
					<key>end</key>
					<string>(")</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.delimiter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)(?&lt;!\$)(\$\$)([[:alpha:]])(([\w$#]){0,29})(?!([\w$#]))</string>
					<key>name</key>
					<string>variable.language</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b([[:alpha:]])(([\w$#]){0,29})(?!([\w$#]))</string>
					<key>name</key>
					<string>variable.other</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b([[:alpha:]])(([\w$#]){30,})</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</array>
		</dict>
		<key>infile</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(badfile|discardfile|infile)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>init</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(defaultif|nullif)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>inner-bfile</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(constant)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>inner-dgen</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(count|max)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>inner-lobfile</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(byteorder(mark)?|c(h(aracterset|eck)|onstant)|length|nocheck|semantics)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(b(ig|yte)|char(acter)?|endian|little)\b</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</array>
		</dict>
		<key>inner-parens</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.delimiter</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inner-parens</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant-numeric</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#inner-dgen</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#inner-ref</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#inner-bfile</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#inner-lobfile</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#inner-sdf</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#filler</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#datatype</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#col</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bfile</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(,|\*|\+|-|:)</string>
							<key>name</key>
							<string>keyword.other.delimiter</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#identifier</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>inner-ref</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(constant)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>inner-sdf</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(byteorder(mark)?|c(h(aracterset|eck)|onstant)|length|nocheck|readsize|semantics)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(b(ig|yte)|char(acter)?|endian|little)\b</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</array>
		</dict>
		<key>into</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(append|blanks|c(heck_constraints|sv)|d(ate|elete|isabled_constraints)|e(mbedded|valuate|xceptions)|f(ields|ormat)|in(dexes|to)|n(o|ull(cols|if))|re(enable|place|sume)|s(inglerow|kip|orted)|t(able|imestamp|r(ailing|uncate))|using|w(hen|ith(out)?)|yes)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>load</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(append|b(lanks|yteorder(mark)?)|c(h(aracterset|eck)|ontinue_load)|data|fi(eld|le(s)?)|i(gnore|nsert)|l(ength|oad)|n(ames|ocheck)|preserve|re(ad(buffers|size)|place)semantics|truncate)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(all|b(ig|yte)|char(acter)?|endian|first|little|none|recoverable|unrecoverable)\b</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(begindata)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*+$</string>
					<key>name</key>
					<string>string.quoted.single</string>
				</dict>
			</array>
		</dict>
		<key>lobfile</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(lobfile)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>nested</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(nested|table)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>oid</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(oid)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>options</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\b(options)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(\()</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.delimiter</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(\))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comment</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#string</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>(\()</string>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>keyword.other.delimiter</string>
										</dict>
									</dict>
									<key>end</key>
									<string>(\))</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#comment</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#storage-clause-parens</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#silent</string>
										</dict>
										<dict>
											<key>match</key>
											<string>(,)</string>
											<key>name</key>
											<string>keyword.operator</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#constant-numeric</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>match</key>
									<string>(?i)\b(columnarrayrows|bindsize|d(ate_cache|egree_of_parallelism|irect)|e(rrors|xternal_table)|file|load|multithreading|parallel|r(e(adsize|sumable(_(name|timeout))?)|ows)|s(ilent|kip(_(index_maintenance|unusable_indexes))?|t(orage|reamsize))|trim)\b</string>
									<key>name</key>
									<string>keyword.control</string>
								</dict>
								<dict>
									<key>match</key>
									<string>(?i)\b(auto|default|false|none|true)\b</string>
									<key>name</key>
									<string>constant.language</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#silent</string>
								</dict>
								<dict>
									<key>match</key>
									<string>(=)</string>
									<key>name</key>
									<string>keyword.operator</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#constant-numeric</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>parens</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.delimiter</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant-numeric</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#dgen</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#ref</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#sid</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#init</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bfile</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#scalar</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lobfile</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#datatype</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#col</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#collection</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#inner-parens</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#identifier</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>keyword.other.delimiter</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>ref</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(ref)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>scalar</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(p(ieced|osition))\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>sdf</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(sdf)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>sid</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(sid)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>silent</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(all|discards|feedback|header|errors|partitions)\b</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</array>
		</dict>
		<key>size-clause</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(\d++)\s*+(E|G|K|M|P|T)\b</string>
		</dict>
		<key>storage-clause-parens</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>storage-clause-parens</string>
					<key>match</key>
					<string>(?i)\b(buffer_pool|default|encrypt|f(lash_cache|reelist(s)?)|keep|groups|initial|m(axextents|inextents)|n(ext|one|ull)|optimal|pctincrease|recycle|unlimited)\b</string>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#size-clause</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#maxsize-clause</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(")</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.delimiter</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(")</string>
					<key>name</key>
					<string>string.quoted.double</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.delimiter</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.character</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\\)(")</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((x|X)?')</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.delimiter</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')</string>
					<key>name</key>
					<string>string.quoted.single</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.delimiter</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.character</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\\)(')</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>termination</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(by|terminated|whitespace)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(eof)\b</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</array>
		</dict>
		<key>varray</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(varray)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.oracle.sqlloader</string>
	<key>uuid</key>
	<string>8a0e417e-97a9-4442-9c87-3575a06538b6</string>
</dict>
</plist>
