<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>uuid</key>
        <string>8A285AB0-38C8-4A47-BAC9-BCAB6D5FE44D</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>name</key>
                <string>comment.line.double-dash</string>
                <key>match</key>
                <string>\s*(\-\-).*$</string>
            </dict>
            <dict>
                <key>name</key>
                <string>comment.line.character</string>
                <key>match</key>
                <string>\s*(rem|remark|#)\b.*$</string>
            </dict>
            <dict>
                <key>name</key>
                <string>comment.line.documentation</string>
                <key>match</key>
                <string>\s*/\*.*\*/.*$'</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>/\*</string>
                <key>name</key>
                <string>comment.block</string>
                <key>end</key>
                <string>\*/</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.numeric.oracle</string>
                <key>match</key>
                <string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>'</string>
                <key>name</key>
                <string>string.quoted.single.oracle</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>keyword.operator.oracle</string>
                        <key>match</key>
                        <string>&amp;|\:|/|\=|\+|\.</string>
                    </dict>
                </array>
                <key>end</key>
                <string>'</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.operator.oracle</string>
                <key>match</key>
                <string>\-|&amp;|\+|/|\*|%|\.|=|!=|&gt;|@|&lt;|\:=|,|\|\||\;|\b(?i:and|or|union|exists|having|not|xor|join|on|in|is|out|between|any|asc|desc|of|current|all|over|partition|minus|into|bulk|collect|by|prior)\b|\(|\)</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>"</string>
                <key>name</key>
                <string>string.quoted.double.oracle</string>
                <key>end</key>
                <string>"</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.oracle.ddl</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.operator.oracle</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.function.oracle</string>
                <key>match</key>
                <string>^\s*(\b(?i:function|procedure)\b)(.*)(\()</string>
            </dict>
            <dict>
                <key>name</key>
                <string>storage.type.oracle</string>
                <key>match</key>
                <string>\b(?i:char|varchar|record|autonomous_transaction|varchar2|integer|number|int|type|rowtype|boolean|varray|table|date|xmltype|long|clob|blob|timestamp|cursor|binary_integer|exception)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>storage.modifier.oracle</string>
                <key>match</key>
                <string>\b(?i:constant|default|nocopy)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>support.function.oracle</string>
                <key>match</key>
                <string>\b(?i:nvl|translate|rank|avg|chr|(get|create|constraint|is|init|run|put|set|validate|set|add|format|debug|update).*?(\(|\;)?|to_char|sum|to_date|extract|dbms_utility|dbms_job|greatest|least|fnd_log|fnd_date|fnd_global|trim|lpad|rpad|instr|decode|substr|xmlagg|xmlattributes|xmlroot|xmlelement|xmlforest|fnd_program|fnd_file|to_number|dbms_output|dbms_lob|fnd_profile|utl_file|rtrim|ltrim|trunc|replace|abs|length|regexp_like|regexp_replace|upper|lower|extractvalue|xmlexists|passing|path|xmltable|updatexml|wf_engine|xmlnamespaces|fnd_set|dbms_application_info|max|min|count|xmlconcat|dbms_output|regexp_like|regexp_substr)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.pl</string>
                <key>match</key>
                <string>\b(?i:begin|end|case|if|then|while|exit|open|close|fetch|return|raise|raise_application_error|else|for|with|execute|immediate|is|as|goto|until|when|elsif|declare|language|java|name|when|loop|first|last|next)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.sql</string>
                <key>match</key>
                <string>\b(?i:commit|rollback|savepoint)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.fndload</string>
                <key>match</key>
                <string>\b(?i:download|upload|key|base|ctx|trans)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.sqlplus</string>
                <key>match</key>
                <string>\b(?i:tab|longc|longchunk|lobof|loboffset|noprint|lines|space|columns|center|whenever|sqlerror|oserror|failure|arraysize|disc|disconnect|conn|connect|linesize|trimspool|def|define|verify|feedback|prompt|serveroutput|rem|remark|pages|pagesize|head|time|heading|format|truncate|wrap|show|showmode|echo|timing|newpage|clear|pno|skip|ttitle|btitle|breaks|computes|new_value|err|errors|spool|off|col|termout|sqlprompt|word|wrapped|size)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.other.dml.oracle</string>
                <key>match</key>
                <string>\b(?i:select|distinct|from|where|group|order|connect|join|left|right|outer|values|update|merge|matched|insert|delete|set|returning|using)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.other.ddl.oracle</string>
                <key>match</key>
                <string>\b(?i:alter|trigger|new|old|referencing|each|row|before|after|modify|disable|synonym|sequence|increment|start|authid|current_user|create|replace|table|view|column|procedure|function|package|object|comment|drop|grant|to|index|unique|check|body|compile|index)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.other</string>
                <key>match</key>
                <string>\b(?i:(l|v||g|c|t|pl)(_)[A-Za-z0-9_]*)\b|\b[A-Za-z0-9_]*\.|\b(?i:[A-Za-z0-9_]*)(_)(tb|c|r|t|type|arr|tab|tbl|rec)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.parameter</string>
                <key>match</key>
                <string>\b(?i:(p|b|x)(_)[A-Za-z0-9_]*)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.language.oracle</string>
                <key>match</key>
                <string>\b(?i:true|false|currval|nextval|found|notfound|rownum|null|pragma|others|no_data_found|too_many_rows|isopen|sysdate|errbuf|retcode|sysdate|systimestamp|user|sqlerrm|sqlcode|dual|(v|gv)\$([[:alpha:]_])*|(all|dba|user)_([:alpha:]*)?|rowid|rowcount|sql|like|itemkey|funcmode|actid|([[:alpha:]_])*_(all|vl|v|b|tl|number|code|id|source|num|level|flag|msg|status|rate|name|date|method)|itemtype)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.language.oracle.apps</string>
                <key>match</key>
                <string>\b(?i:created_by|creation_date|last_updated_by|last_update_date|attribute[0-9]*|last_update_login|org_id|(fnd|fv|int|zx|inv|pa|hr|per|fa|ar|ra|hz|iby|rcv|ap|po|gl|ce)_.*?|owner|segment[0-9]*)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.character.oracle</string>
                <key>match</key>
                <string>\b(?i:row_id|apps)\b</string>
            </dict>
        </array>
        <key>name</key>
        <string>Oracle</string>
        <key>scopeName</key>
        <string>source.oracle</string>
        <key>fileTypes</key>
        <array>
            <string>sql</string>
            <string>SQL</string>
            <string>pls</string>
            <string>PLS</string>
            <string>pks</string>
            <string>PKS</string>
            <string>pkb</string>
            <string>PKB</string>
            <string>pkh</string>
            <string>PKH</string>
            <string>ldt</string>
            <string>LDT</string>
            <string>ctl</string>
            <string>CTL</string>
            <string>plb</string>
            <string>PLB</string>
            <string>pkg</string>
            <string>PKG</string>
            <string>lct</string>
            <string>LCT</string>
        </array>
        <key>foldingStopMarker</key>
        <string>^\s*(?i:\b(end|close|(end if)|(end loop))\b)</string>
        <key>foldingStartMarker</key>
        <string>^\s*(?i:\b(begin|then|define|loop|open|create|case)\b)</string>
    </dict>
</plist>
