<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>oracle</string>
		<string>pls</string>
		<string>plb</string>
		<string>buf</string>
	</array>
	<key>name</key>
	<string>Oracle SQL*Plus Script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#oracle-code</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>date-constant</key>
		<dict>
			<key>match</key>
			<string>\b(?i:date|(to )?(day|hour|minute|second)|timestamp|at time zone|interval|(to )?(year|month))\b</string>
			<key>name</key>
			<string>constant.date.oracle</string>
		</dict>
		<key>functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sql-function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-functions</string>
				</dict>
			</array>
		</dict>
		<key>numeric-constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.oracle.delimiter</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.oracle.delimiter</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.oracle.delimiter</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.oracle.delimiter</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.oracle.delimiter</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Numeric constants in various formats (decimal, scientific)</string>
					<key>match</key>
					<string>\b(\+|-)?[0-9]+((e|E)(\+|-)?|f|F|d|D)?((\.)[0-9]+(d|D|f|F))?\b</string>
					<key>name</key>
					<string>constant.numeric.oracle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:binary_double_infinity|binary_double_nan|binary_float_infinity|binary_float_nan)\b</string>
					<key>name</key>
					<string>constant.numeric.oracle</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sql-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-operator</string>
				</dict>
			</array>
		</dict>
		<key>oracle-code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sqlplus-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-code</string>
				</dict>
			</array>
		</dict>
		<key>plsql</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#plsql-subprogram</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-block</string>
				</dict>
			</array>
		</dict>
		<key>plsql-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#plsql-block-declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-block-executable</string>
				</dict>
			</array>
		</dict>
		<key>plsql-block-conditional</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#plsql-block-conditional-if</string>
				</dict>
			</array>
		</dict>
		<key>plsql-block-conditional-if</key>
		<dict>
			<key>begin</key>
			<string>(\b(?i:if)\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.plsql.conditional</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\b(?i:end))\s+(\b(?i:if)\b)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.oracle.plsql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.oracle.plsql</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>comment.block</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.oracle.delimiter</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.control.conditional.if</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#plsql-block-executable-include</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=(i|I)(f|F))\b</string>
					<key>end</key>
					<string>(?=\b(?i:then)\b)</string>
					<key>name</key>
					<string>meta.block.control.conditional.condition</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numeric-constant</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#functions</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=(t|T)(h|H)(e|E)(n|N))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.plsql.conditional</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*(?i:elsif|else|end\s+\if)\b)</string>
					<key>name</key>
					<string>meta.block.control.conditional.section.main</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#plsql-block-executable-include</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b((?i:elsif))\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.plsql.conditional</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*(?i:elsif|else|end\s+\if)\b)</string>
					<key>name</key>
					<string>meta.block.control.conditional.section.elsif</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#plsql-block-executable-include</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b((?i:else))\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.plsql.conditional</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s*(?i:end\s+\if)\b)</string>
					<key>name</key>
					<string>meta.block.control.conditional.section.else</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#plsql-block-executable-include</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>plsql-block-control</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#plsql-block-loop</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-block-conditional</string>
				</dict>
			</array>
		</dict>
		<key>plsql-block-declaration</key>
		<dict>
			<key>begin</key>
			<string>\b((?i:declare))\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.oracle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(?i:begin))</string>
			<key>name</key>
			<string>meta.block.declaration</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#plsql-include-declaration</string>
				</dict>
			</array>
		</dict>
		<key>plsql-block-exception</key>
		<dict>
			<key>begin</key>
			<string>\b((?i:exception))\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.oracle.plsql</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^\s*(?i:end))</string>
			<key>name</key>
			<string>meta.block.exception</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i:(when)\s+(\S+)\s+(then))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.plsql</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.plsql</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^\s*(?i:end|when))</string>
					<key>name</key>
					<string>meta.block.exception.condition</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#plsql-block-executable-include</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>plsql-block-executable</key>
		<dict>
			<key>begin</key>
			<string>(\b(?i:begin)\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.oracle.plsql</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\b(?i:end))(\s+(?!\b(?i:if|case|loop)\b)\w+)?\s*(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.oracl.plsql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.subprogram.oracle</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.oracle.delimiter</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.executable.oracle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#plsql-block-executable-include</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-block-exception</string>
				</dict>
			</array>
		</dict>
		<key>plsql-block-executable-include</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-block-control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-dml-select-columns</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-dml-keywords</string>
				</dict>
			</array>
		</dict>
		<key>plsql-block-loop</key>
		<dict>
			<key>begin</key>
			<string>(\b(?i:loop)\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.oracl.plsql</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\b(?i:end))\s+(\b(?i:loop)\b)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.oracle.plsql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.oracle.plsql</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>comment.block</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.oracle.delimiter</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block.control.loop</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#plsql-block-executable-include</string>
				</dict>
			</array>
		</dict>
		<key>plsql-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Oracle PL/SQL single line double-dash comment.</string>
					<key>match</key>
					<string>\s*(--).*$</string>
					<key>name</key>
					<string>comment.line.double-dash.iso.oracle</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(/\*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Oracle PL/SQL Block comment.</string>
					<key>end</key>
					<string>(\*/)</string>
					<key>name</key>
					<string>comment.block.plsql.oracle</string>
				</dict>
			</array>
		</dict>
		<key>plsql-cursor-declaration</key>
		<dict>
			<key>begin</key>
			<string>((?i:cursor))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.oracle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=;)</string>
			<key>name</key>
			<string>meta.type.plsql.cursor</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=(c|C)(u|U)(r|R)(s|S)(o|O)(r|R))\s+(\w+)</string>
					<key>name</key>
					<string>variable.other</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:return|is)\b</string>
					<key>name</key>
					<string>storage.type.modifier</string>
				</dict>
				<dict>
					<key>match</key>
					<string>%</string>
					<key>name</key>
					<string>keyword.operator.oracle.delimiter</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=(r|R)(e|E)(t|T)(u|U)(r|R)(n|N))\s+((\w)+)</string>
					<key>name</key>
					<string>storage.type.oracle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=%)\w+</string>
					<key>name</key>
					<string>storage.type.oracle</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-dml-select</string>
				</dict>
			</array>
		</dict>
		<key>plsql-function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:dbms_output)\b</string>
					<key>name</key>
					<string>support.function.plsql.rdbms</string>
				</dict>
			</array>
		</dict>
		<key>plsql-function-apps</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:ame_api[1-9])\b</string>
					<key>name</key>
					<string>support.function.plsql.apps.ame</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:app_exception|fnd_date|fnd_global|fnd_log|fnd_log_repository|fnd_message|fnd_profile|fnd_file|mo_global)\b</string>
					<key>name</key>
					<string>support.function.plsql.apps.fnd</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:wf_core|wf_directory|wf_engine|wf_event|wf_lookup_types_pub|wf_notification)\b</string>
					<key>name</key>
					<string>support.function.plsql.apps.wf</string>
				</dict>
			</array>
		</dict>
		<key>plsql-functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#plsql-function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-function-apps</string>
				</dict>
			</array>
		</dict>
		<key>plsql-include-declaration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-cursor-declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-record-declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-storage</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric-constant</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:false|null|true)\b</string>
					<key>name</key>
					<string>constant.language.oracle</string>
				</dict>
				<dict>
					<key>include</key>
					<string>functions</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=:=)\s+(?!(?i:null|true|false))((?![0-9])(\w))+\s*(?=;)</string>
					<key>name</key>
					<string>variable.other</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:(p|x)_\w+)\b</string>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=(t|T)(y|Y)(p|P)(e|E))\s+(\w+)\s+(?=(?i:is))</string>
					<key>name</key>
					<string>variable.other</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-subprogram</string>
				</dict>
			</array>
		</dict>
		<key>plsql-keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:continue|exit|for|goto|then|while)\b</string>
					<key>name</key>
					<string>keyword.control.plsql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:close|fetch|open)\b</string>
					<key>name</key>
					<string>keyword.other.plsql</string>
				</dict>
			</array>
		</dict>
		<key>plsql-operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\+|-|\*|/)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\|\|)</string>
					<key>name</key>
					<string>keyword.operator.concatenation</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:intersect|minus|union( all)?)\b</string>
					<key>name</key>
					<string>keyword.operator.set</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?i:multiset (except|intercept|union)( (all|distinct))?)\b</string>
					<key>name</key>
					<string>keyword.operator.multiset</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\:=|=&gt;|%|\.|\*\*|\(|\)|\:|,|&lt;&lt;|&gt;&gt;|\.\.|=|&lt;&gt;|!=|~=|\^=|&lt;|&gt;|&lt;=|&gt;=|@)|;</string>
					<key>name</key>
					<string>keyword.operator.oracle.delimiter</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:and|between|(not )?in|is (not )?null|like|not|or|escape)\b</string>
					<key>name</key>
					<string>keyword.operator.oracle.expression</string>
				</dict>
			</array>
		</dict>
		<key>plsql-record-declaration</key>
		<dict>
			<key>begin</key>
			<string>(?i:(is) (record))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.oracle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.oracle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=;)</string>
			<key>name</key>
			<string>meta.name.type.plsql.record</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*(?!(?i:procedure|function|cursor|type))([A-Za-z]\w*)</string>
					<key>name</key>
					<string>variable.other</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-storage</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-storage</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:false|null|true)\b</string>
					<key>name</key>
					<string>constant.language.oracle</string>
				</dict>
			</array>
		</dict>
		<key>plsql-storage</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:binary_integer|boolean|clob|date|exception|is table of|long|number|pls_integer|varchar2)\b</string>
					<key>name</key>
					<string>storage.type.oracle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Za-z]\w*(?=\.|%)|\b(?i:type)\b</string>
					<key>name</key>
					<string>storage.type.user.oracle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\.)[A-Za-z]\w*</string>
					<key>name</key>
					<string>storage.type.user.oracle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:constant|cursor|default|in|index by|integer|nocopy|not|out|(?&lt;=%)type|rowtype)\b</string>
					<key>name</key>
					<string>storage.modifier.oracle</string>
				</dict>
			</array>
		</dict>
		<key>plsql-subprogram</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#plsql-subprogram-heading</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-subprogram-declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-subprogram-body</string>
				</dict>
			</array>
		</dict>
		<key>plsql-subprogram-body</key>
		<dict>
			<key>begin</key>
			<string>((?i:begin))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.oracl.plsql</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\b(?i:end))(\s+(?!\b(?i:if|case|loop)\b)\w+)?\s*(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.oracl.plsql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.subprogram.oracle</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.oracl.delimiter</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.subprogram.body.oracle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#plsql-block-executable-include</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-block-exception</string>
				</dict>
			</array>
		</dict>
		<key>plsql-subprogram-declaration</key>
		<dict>
			<key>begin</key>
			<string>\b((?i:is(?!\s*(not|null|table))|as))\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.oracle.ddl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s*(?=(?i:begin))</string>
			<key>name</key>
			<string>meta.subprogram.declaration.oracle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#plsql-include-declaration</string>
				</dict>
			</array>
		</dict>
		<key>plsql-subprogram-heading</key>
		<dict>
			<key>begin</key>
			<string>\b((?i:procedure|function))\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.subprogram.identifier.oracle</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.oracle.ddl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.subprogram.oracle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)|(?=\s*(?i:is|as(?! language)))\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.oracle.delimiter</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.subprogram.heading.oracle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.oracle.ddl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.oracle</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((?i:return))\s+((\w|\.)+)</string>
					<key>name</key>
					<string>meta.subprogram.type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#plsql-storage</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(,|\.|%|:=|\(|\))</string>
					<key>name</key>
					<string>keyword.operator.oracle.delimiter</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:false|null|true)\b</string>
					<key>name</key>
					<string>constant.language.oracle</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:errbuf|retcode)\b</string>
					<key>name</key>
					<string>constant.language.oracle.apps</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=:=)\s+((?![0-9])(\w|\.))+</string>
					<key>name</key>
					<string>variable.other</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=(d|E)(f|F)(a|A)(u|U)(l|L)(t|T))\s+(?!(?i:null|true|false))((?![0-9])(\w|\.))+</string>
					<key>name</key>
					<string>variable.other</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric-constant</string>
				</dict>
			</array>
		</dict>
		<key>sql-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(--)[^+]</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>SQL ISO Single line double-dash comment</string>
					<key>end</key>
					<string>(?=;)|\s*$</string>
					<key>name</key>
					<string>comment.line.double-dash.iso.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sqlplus-variable-substitution</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(/\*)[^+]</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>SQL Block comment.</string>
					<key>end</key>
					<string>(\*/)</string>
					<key>name</key>
					<string>comment.block.sql.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sqlplus-variable-substitution</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sql-ddl</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i:(create)(\s|\n)\s*(?!or|package|function|procedure|trigger)(\w+))|(?i:(create)(\s|\n)+(or)(\s|\n)+(replace)(\s|\n)\s*(?!or|pa|fu|pr|tr)(\w+))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.sql.ddl</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>keyword.other.sql.ddl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.sql.ddl</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other.sql.ddl</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.other.sql.ddl</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>keyword.other.sql.ddl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.oracle.delimiter</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.diff</string>
				</dict>
			</array>
		</dict>
		<key>sql-dml</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sql-dml-select</string>
				</dict>
			</array>
		</dict>
		<key>sql-dml-keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sql-dml-keywords-common</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-dml-keywords-select</string>
				</dict>
			</array>
		</dict>
		<key>sql-dml-keywords-common</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:for|from|into|join|left|on|outer|partition( for)?|right|subpartition( for)?|where)\b</string>
					<key>name</key>
					<string>keyword.other.oracle.dml.common</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:nextval|currval)\b</string>
					<key>name</key>
					<string>support.variable</string>
				</dict>
			</array>
		</dict>
		<key>sql-dml-keywords-select</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:as|connect by|select|order (siblings)?by|start with)\b</string>
					<key>name</key>
					<string>keyword.other.other.oracle.dml.select</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:prior|connect_by_root)\b</string>
					<key>name</key>
					<string>keyword.operator.query.hierarchichal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(asc|desc|nulls (first|last))\b</string>
					<key>name</key>
					<string>support.constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-dml-keywords-common</string>
				</dict>
			</array>
		</dict>
		<key>sql-dml-select</key>
		<dict>
			<key>begin</key>
			<string>\b((?i:select))\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.oracle.dml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=;)|^(/|\.)</string>
			<key>name</key>
			<string>meta.sql.dml.select</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sql-dml-hint</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-pseudocolumn</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-support-function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-dml-keywords-common</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-dml-keywords-select</string>
				</dict>
			</array>
		</dict>
		<key>sql-dml-select-columns</key>
		<dict>
			<key>begin</key>
			<string>\b(?i:(select))\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.oracle.dml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b((?i:from))\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.oracle.dml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.diff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-dml-select-columns</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-dml-keywords-select</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-dml-hint</string>
				</dict>
			</array>
		</dict>
		<key>sql-functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:abs|acos|asin|atan|atan2|bitand|ceil|cos|cosh|exp|floor|ln|log|mod|nanvl|power|remainder|round|sign|sin|sinh|sqrt|tan|tanh|trunc|width_bucket)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.numeric</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:chr|concat|initcap|lower|lpad|ltrim|nchr|nls_initcap|nls_lower|nls_upper|nlssort|regexp_replace|regexp_substr|replace|rpad|rtrim|soundex|substr(b)?|translate|trim|upper)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.char.return-char</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?i:using(\s+(char_cs|char_ns)))\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.char.return-char</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:ascii|instr(b)?|length(b)?|regexp_count|regexp_inst)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.char.return-number</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:nls_charset_decl_len|nls_charset_id|nls_charset_name)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.char.return-nls</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:add_months|current_date|current_timestamp|dbtimezone|extract|from_tz|last_day|localtimestamp|months_between|new_time|next_day|numtodsinterval|numtoyminterval|ora_dst_affected|ora_dst_convert|ora_dst_error|round|sessiontimezone|sys_extract_utc|sysdate|systimestamp|to_cha |to_dsinterval|to_timestamp|to_timestamp_tz|to_yminterval|trunc|tz_offset)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.datetime</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:greatest|least)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.comparison</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:asciistr|bin_to_num|cast|chartorowid|compose|convert|decompose|hextoraw|numtodsinterval|numtoyminterval|rawtohex|rawtonhex|rowidtochar|rowidtonchar|scn_to_timestamp|timestamp_to_scn|to_binary_double|to_binary_float|to_blob|to_char|to_char|to_char|to_clob|to_date|to_dsinterval|to_lob|to_multi_byte|to_nchar|to_nchar|to_nchar|to_nclob|to_number|to_single_byte|to_timestamp|to_timestamp_tz|to_yminterval|treat|unistr)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.conversion</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:bfilename|empty_blob|empty_clob)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.large-object</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:cardinality|collect|powermultiset|powermultiset_by_cardinality|set\()\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.collection</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:sys_connect_by_path)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.hierarchichal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:cluster_id|cluster_probability|cluster_set|feature_id|feature_set|feature_value|prediction|prediction_bounds|prediction_cost|prediction_details|prediction_probability|prediction_set)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.data-mining</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:appendchildxml|deletexml|depth|existsnode|extract|extractvalue|insertchildxml|insertchildxmlafter|insertchildxmlbefore|insertxmlafter|insertxmlbefore|path|sys_dburigen|sys_xmlagg|sys_xmlgen|updatexml|xmlagg|xmlcast|xmlcdata|xmlcolattval|xmlcomment|xmlconcat|xmldiff|xmlelement|xmlexists|xmlforest|xmlisvalid|xmlparse|xmlpatch|xmlpi|xmlquery|xmlroot|xmlsequence|xmlserialize|xmltable|xmltransform)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.xml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:decode|dump|ora_hash|vsize)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.codec</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:coalesce|lnnvl|nanvl|nullif|nvl|nvl2)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.null-related</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:sys_context|sys_guid|sys_typeid|uid|user|userenv)\b</string>
					<key>name</key>
					<string>support.function.sql.single-row.environment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:avg|collect|corr|corr_k|corr_s|count|covar_pop|covar_samp|cume_dist|dense_rank|first|group_id|grouping|grouping_id|last|listagg|max|median|min|over|percent_rank|percentile_cont|percentile_disc|rank|regr_slope|regr_intercept|regr_count|regr_r2|regr_avgx|regr_avgy|regr_sxx|regr_syy|regr_sxy|stats_binomial_test|stats_crosstab|stats_f_test|stats_ks_test|stats_mode|stats_mw_test|stats_one_way_anova|stats_t_test_indep|stats_t_test_indepu|stats_t_test_one|stats_t_test_paired|stats_wsr_test|stddev|stddev_pop|stddev_samp|sum|sys_xmlagg|var_pop|var_samp|variance|xmlagg)\b</string>
					<key>name</key>
					<string>support.function.sql.aggregate</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:cume_dist|dense_rank|first|following|lag|last|lead|listagg|ntile|percent_rank|percentile_(cont|disc)|rank|ratio_to_report|row_number|preceding|rows|range|unbounded (preceding|following)|current row)\b</string>
					<key>name</key>
					<string>support.function.sql.analytics</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:deref|make_ref|ref|reftohex|value)\b</string>
					<key>name</key>
					<string>support.function.sql.object-reference</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:cv|iteration_number|presentnnv|presentv|previous)\b</string>
					<key>name</key>
					<string>support.function.sql.model</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:cube_table)\b</string>
					<key>name</key>
					<string>support.function.sql.olap</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:dataobj_to_partition)\b</string>
					<key>name</key>
					<string>support.function.sql.data-cartridge</string>
				</dict>
			</array>
		</dict>
		<key>sql-hint</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>SQL Hint using double dash syntax.</string>
					<key>match</key>
					<string>(?&lt;=((s|S)(e|E)(l|L)(e|E)(c|C)(t|T))|((i|I)(n|N)(s|S)(e|E)(r|R)(t|T))|((u|U)(p|P)(d|D)(a|A)(t|T)(e|E))|((d|D)(e|E)(l|L)(e|E)(t|T)(e|E))|((m|M)(e|E)(r|R)(g|G)(e|E)))\s*(--\+).*$</string>
					<key>name</key>
					<string>string.interpolated.oracle.sql</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=((s|S)(e|E)(l|L)(e|E)(c|C)(t|T))|((i|I)(n|N)(s|S)(e|E)(r|R)(t|T))|((u|U)(p|P)(d|D)(a|A)(t|T)(e|E))|((d|D)(e|E)(l|L)(e|E)(t|T)(e|E))|((m|M)(e|E)(r|R)(g|G)(e|E))|((c|C)(r|R)(e|E)(a|A)(t|T)(e|E)))\s*(/\*\+)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>SQL Hint using double dash syntax.</string>
					<key>end</key>
					<string>(\*/)</string>
					<key>name</key>
					<string>comment.block</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(,|\(|\)|\.|\$|@)</string>
							<key>name</key>
							<string>keyword.operator.delimiter.oracle</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numeric-constant</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b(?i:all_rows|append|append_values|cache|change_dupkey_error_index|cluster|cursor_sharing_exact|driving_site|dynamic_sampling|fact|first_rows|full|hash|ignore_row_on_dupkey_index|index|index_asc|index_combine|index_desc|index_ffs|index_join|index_ss|index_ss_asc|index_ss_desc|leading|merge|model_min_analysis|monitor|native_full_outer_join|no_expand|no_fact|no_index|no_index_ffs|no_index_ss|no_merge|no_monitor|no_native_full_outer_join|no_parallel|no_parallel_index|no_push_pred|no_push_subq|no_px_join_filter|no_query_transformation|no_result_cache|no_rewrite|no_star_transformation|no_statement_queuing|no_unnest|no_use_hash|no_use_merge|no_use_nl|no_xml_query_rewrite|no_xmlindex_rewrite|noappend|nocache|opt_param|ordered|parallel|parallel_index|pq_distribute|push_pred|push_subq|px_join_filter|qb_name|result_cache|retry_on_row_change|rewrite|star_transformation|statement_queuing|unnest|use_concat|use_hash|use_merge|use_nl|use_nl_with_index)\b</string>
							<key>name</key>
							<string>keyword.other.hint.oracle</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b(?i:auto|broadcast|default|hash|local|manual|none|partition|random)\b</string>
							<key>name</key>
							<string>support.constant.hint.oracle</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b(?i:noparallel|norewrite|rule)\b</string>
							<key>name</key>
							<string>invalid.deprecated</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sql-operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\+|-|\*|/)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\|\|)</string>
					<key>name</key>
					<string>keyword.operator.concatenation</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:intersect|minus|union( all)?)\b</string>
					<key>name</key>
					<string>keyword.operator.set</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?i:multiset (except|intercept|union)( (all|distinct))?)\b</string>
					<key>name</key>
					<string>keyword.operator.multiset</string>
				</dict>
			</array>
		</dict>
		<key>sql-pseudocolumn</key>
		<dict>
			<key>match</key>
			<string>\b((?i:column_value|connect_by_iscycle|connect_by_isleaf|currval|level|nextval|object_id|object_value|ora_rowscn|rowid|rownum|sysdate|systimestamp|versions_endscn|versions_endtime|versions_startscn|versions_starttime|versions_operation|versions_xid|xmldata))\b</string>
			<key>name</key>
			<string>support.variable.sql.oracle</string>
		</dict>
		<key>sql-query</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sql-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql-hint</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>meta.diff</string>
				</dict>
			</array>
		</dict>
		<key>sql-strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.sqlplus.oracle</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.sql.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sqlplus-variable-substitution</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.sqlplus.oracle</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.sql.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sqlplus-variable-substitution</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sqlplus-code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sqlplus-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sqlplus-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sqlplus-commands</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sqlplus-container-sql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sqlplus-container-plsql</string>
				</dict>
			</array>
		</dict>
		<key>sqlplus-command-string-parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.sqlplus.oracle</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.sql.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sqlplus-variable-substitution</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.sqlplus.oracle</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.sql.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sqlplus-variable-substitution</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sqlplus-commands</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*((?i:rem(a|ar|ark)?))\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>SQL*Plus REM[ARK].</string>
					<key>end</key>
					<string>[^\-\n]$|^$</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.line.character.sqlplus.oracle</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.command.remark.sqlplus.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\-$</string>
							<key>name</key>
							<string>keyword.other.delimiter.plsql.oracle</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>comment.line.character.sqlplus.oracle</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:desc(ribe|rib|ri|r))\b</string>
					<key>name</key>
					<string>keyword.other.sqlplus.oracle</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(@{1,2}|(?i:start))\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.sqlplus.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Run a script</string>
					<key>end</key>
					<string>(\s*$)</string>
					<key>name</key>
					<string>meta.command.run-script.sqlplus.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sqlplus-command-string-parameters</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?=\s*)(\S+)</string>
							<key>name</key>
							<string>variable.parameter.sqlplus.oracle</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^.*(?=(?i:def(ine|in|i)?))</string>
					<key>end</key>
					<string>\.*$</string>
					<key>name</key>
					<string>meta.command.define.sqlplus.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>((?i:def(ine|in|i)?))\s+(?=\S+)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.sqlplus.oracle</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>variable.other.sqlplus.oracle</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=\s|=)</string>
							<key>name</key>
							<string>meta.command.define.name.sqlplus.oracle</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#sqlplus-variable-substitution</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\s*(=)\s*(?=\S+)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.operator.sqlplus.oracle</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\s|$</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#sqlplus-variable-substitution</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#sqlplus-command-string-parameters</string>
								</dict>
								<dict>
									<key>match</key>
									<string>(\S+)</string>
									<key>name</key>
									<string>variable.parameter.sqlplus.oracle</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>invalid.deprecated</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*((?i:exit|quit)\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.sqlpls.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>SQL*Plus terminate session</string>
					<key>end</key>
					<string>\s*$</string>
					<key>name</key>
					<string>meta.command.exit.sqlplus.oracle</string>
				</dict>
			</array>
		</dict>
		<key>sqlplus-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(--)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>ISO Single line double-dash comment.</string>
					<key>end</key>
					<string>\s*$</string>
					<key>name</key>
					<string>comment.line.double-dash.iso.oracle</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Invalid ISO Single line double-dash comment.</string>
					<key>match</key>
					<string>(?&lt;!^)(?:\s*)(--.*)$</string>
					<key>name</key>
					<string>comment.line.double-dash.iso.oracle</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(/\*)\s</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Oracle SQ*Plus Block comment.</string>
					<key>end</key>
					<string>(\*/)</string>
					<key>name</key>
					<string>comment.block.sqlplus.oracle</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(/\*)[^\s]</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Oracle SQ*Plus Block invalid comment.</string>
					<key>end</key>
					<string>(\*/)</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</array>
		</dict>
		<key>sqlplus-container-plsql</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=^\s*(?i:declare|begin)\b)</string>
					<key>end</key>
					<string>^\.\s*$|^\s*/\s*$</string>
					<key>name</key>
					<string>meta.block.plsql.container.sqlplus.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>string.quoted.single</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sqlplus-container-sql</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sqlplus-container-sql-dml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sqlplus-container-sql-ddl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sqlplus-container-sql-query</string>
				</dict>
			</array>
		</dict>
		<key>sqlplus-container-sql-ddl</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=^\s*(?i:create\s+(or\s+replace\s+)?\b))</string>
					<key>end</key>
					<string>^\.\s*$|^\s*/\s*$</string>
					<key>name</key>
					<string>meta.block.ddl.container.sqlplus.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>meta.diff</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sqlplus-container-sql-dml</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=^\s*(?i:insert|update|delete)\b)</string>
					<key>end</key>
					<string>^\.?\s*$|^\s*/\s*$|;</string>
					<key>name</key>
					<string>meta.block.sql.dml.container.sqplus.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>meta.diff</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sqlplus-container-sql-query</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=^\s*(?i:select)\b)</string>
					<key>end</key>
					<string>^(\.)?\s*$|^\s*(/)\s*$|(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.delimiter.sqlplus.oracle</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block.sql.dml.container.sqplus.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sql-query</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sqlplus-strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.sqlplus.oracle</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.sqlplus.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sqlplus-variable-substitution</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delimiter.sqlplus.oracle</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.sqlplus.oracle</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#sqlplus-variable-substitution</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sqlplus-variable-substitution</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.substitution.sqlplus.oracle</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.substitution.sqlplus.oracle</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.substitution.sqplus.oracle</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.concatenation.sqlplus.oracle</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;+)((\s*(&amp;*))*)\s*(\w+)(\.|(?=&amp;))?</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!n|N|q|Q)(')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Single quote string.</string>
					<key>end</key>
					<string>(')</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.oracle</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>&amp;|\:|%|\$</string>
							<key>name</key>
							<string>keyword.operator.oracle</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((n|N)')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Single national quote string.</string>
					<key>end</key>
					<string>(')</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.oracle</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>&amp;|\:|%|\$</string>
							<key>name</key>
							<string>keyword.operator.oracle</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(n|N)?(q|Q)(')([\[\{&lt;\(])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Single alternative quote string matching bracket/parenthesis</string>
					<key>end</key>
					<string>([\]\}&gt;\)])(')</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.oracle</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>&amp;|\:|%|\$|\'</string>
							<key>name</key>
							<string>keyword.operator.oracle</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(n|N)?(q|Q)(')([^\[\{&lt;\(])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Single alternative quote string.</string>
					<key>end</key>
					<string>(\4)(')</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.oracle</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>&amp;|\:|%|\$|\'</string>
							<key>name</key>
							<string>keyword.operator.oracle</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.oracle</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Double quote string.</string>
					<key>end</key>
					<string>(")</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.oracle</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>&amp;|\:|%|\$</string>
							<key>name</key>
							<string>keyword.operator.oracle</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.sqlplus</string>
	<key>uuid</key>
	<string>8d6beb42-5e2b-4aba-b98d-43ad4fc532e7</string>
</dict>
</plist>
